# Generated by Django 3.2.3 on 2021-05-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_model',
            old_name='is_live',
            new_name='is_alive',
        ),
    ]
