# Generated by Django 3.2.3 on 2021-05-28 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_rename_is_live_test_model_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 14, 43, 53, 805242, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 14, 43, 53, 805242, tzinfo=utc)),
        ),
    ]
