# Generated by Django 3.2.3 on 2021-05-28 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_auto_20210528_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_model',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='test_model',
            name='extra_name',
            field=models.CharField(default='null', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 18, 17, 35, 360431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 18, 17, 35, 360431, tzinfo=utc)),
        ),
    ]
