# Generated by Django 3.2.3 on 2021-05-28 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_auto_20210528_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 18, 18, 23, 486382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 18, 18, 23, 486382, tzinfo=utc)),
        ),
    ]
