# Generated by Django 3.2.3 on 2021-05-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_auto_20210528_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 21, 32, 712883)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='extra_name',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 21, 32, 712883)),
        ),
    ]
