# Generated by Django 3.2.3 on 2021-05-28 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_auto_20210528_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 23, 7, 352695)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='extra_name',
            field=models.CharField(default='null', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 23, 7, 352695)),
        ),
    ]
