# Generated by Django 3.2.3 on 2021-05-28 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_auto_20210528_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 26, 48, 193413)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 26, 48, 193413)),
        ),
    ]
