# Generated by Django 3.2.3 on 2021-05-28 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0008_auto_20210528_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_model',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'ModelX'},
        ),
        migrations.AlterField(
            model_name='test_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 33, 57, 98034)),
        ),
        migrations.AlterField(
            model_name='test_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 33, 57, 98034)),
        ),
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 33, 57, 98795))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 28, 13, 33, 57, 98795))),
                ('test_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='tests_app.test_model')),
            ],
        ),
    ]
