# Generated by Django 3.2 on 2021-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
