# Generated by Django 3.2 on 2021-05-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_competitions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tla', models.CharField(max_length=200)),
                ('shortName', models.CharField(max_length=200)),
                ('areaName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
