# Generated by Django 3.2 on 2021-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='tla',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
