# Generated by Django 3.2 on 2021-05-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_teams_tla'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='football.competitions'),
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('position', models.CharField(max_length=200)),
                ('dateOfBirth', models.CharField(max_length=200)),
                ('countryOfBirth', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='football.teams')),
            ],
        ),
    ]
